// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFtlTgZ0D9F5BazkvA6NvfvVekHHQQSJg',
    appId: '1:88128195096:web:1988d4b1a96cad70ca916d',
    messagingSenderId: '88128195096',
    projectId: 'emergency-calls-d324e',
    authDomain: 'emergency-calls-d324e.firebaseapp.com',
    storageBucket: 'emergency-calls-d324e.appspot.com',
    measurementId: 'G-R6KW7XJ905',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMihXVjtPk5X2mQrs3dXrwf2zBObTNaxE',
    appId: '1:88128195096:android:8d36149048405175ca916d',
    messagingSenderId: '88128195096',
    projectId: 'emergency-calls-d324e',
    storageBucket: 'emergency-calls-d324e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-QBs4X5cuX2BpKLcYYGxW1rxDv6WG2g',
    appId: '1:88128195096:ios:bc15b35c3cd78795ca916d',
    messagingSenderId: '88128195096',
    projectId: 'emergency-calls-d324e',
    storageBucket: 'emergency-calls-d324e.appspot.com',
    iosBundleId: 'com.example.emergencyCallApp',
  );
}
